name: Build Arduino sketch

on: [push, pull_request]

jobs:
  build-arduino-sketch:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:avr:mega ./Arduino_code
